### ISSUE TITLE
Leaflet JS maps not loading : Invalid provider (Stamen)

### ISSUE THREAD

**Issue by PaulArgoud** [mcguffin/acf-field-openstreetmap#134]
Hi!

The Leaflet JS based maps are not loading : the map is just solid gray.

WordPress 6.7.1, ACF Pro 6.3.11 and ACF OpenStreetMap Field 1.6.1

This is what I see in my debug console :

![screenshot](https://github.com/user-attachments/assets/802004d1-95fc-4f2a-b51a-eb15580090fc)

At the bottom of this page, you can see the problem : [https://bit.ly/aaeaa2025](https://bit.ly/aaeaa2025)

Thank you in advance for your help and have a nice day !

PS : These problems have been mentioned here : https://wordpress.org/support/topic/leaflet-js-maps-not-loading/

**Comment by patjun** [comment]
Hi,

same here. We updated the plugin today from version 1.5.7 to version 1.6.1.
After that, the map was no longer displayed in the backend.

The console showed the error message: "Uncaught Invalid provider (Stamen)".

After downgrading to 1.5.7 everything works perfectly again.

Can you give me a hint as to where the error might be? I read that I have to change the tile settings. But I couldn't find them in the ACF field.

Many thanks and best regards
Patrick

**Comment by louischance** [comment]
Same issue here, I rolleed back to openstreetmap 1.5.7 and it works back normally.

**Comment by LucasNevesAraujo** [comment]
I had the same issue, but it started working again when I saved the plugin's settings page again, on `/wp-admin/options-general.php?page=acf_osm`.

**Comment by louischance** [comment]
> I had the same issue, but it started working again when I saved the plugin's settings page again, on `/wp-admin/options-general.php?page=acf_osm`.

Mmh.. I just gave it a try, saving twice, clearing the cache and so on, but that doesn't fix the issue for me, I had to roll back again to 1.5.7.

**Comment by room34** [comment]
This issue is still happening for me (as it has been since January), and none of the other methods people have suggested worked. Has this plugin been abandoned, or is there just no forward progress on resolving this issue?

(I should note, the error I get mentions the provider Thunderforest, not Stamen. Not sure if that matters.)
